server:
  port: 8080
  indexingAvailable: true

spring:
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate.enable_lazy_load_no_trans: true
    show-sql: false
  thymeleaf:
    enabled: true
    encoding: UTF-8
  messages.basename: lang.messages
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    useSSL: false
    allowPublicKeyRetrieval: true
    username: root
    password: JopaTest1937098167kot_145

logging:
  level:
    root: INFO
  file.name: logs/info.log

config:
  synchronizePageSave: true
  multiInsertString: insert into search_engine.index(page_id, lemma_id, search_engine.index.rank)

  threadNumberForSites: 12
  threadNumberForPages: 12
  repeatedPageCount: 14
  maxPagesInSite: 400

  sites:
    - url: https://www.sport-express.ru//
      name: Sport-express
      pause: 0
    - url: https://lenta.ru//
      name: Lenta
      pause: 0
    - url: https://6fwear.com//
      name: 6fwear
      pause: 0
